name: Build and Push Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t rihabsouissi/calcule:${{ github.sha }} .
          docker tag rihabsouissi/calcule:${{ github.sha }} rihabsouissi/calcule:v1
          docker tag rihabsouissi/calcule:${{ github.sha }} rihabsouissi/calcule:latest

      - name: Push Docker image
        run: |
          docker push rihabsouissi/calcule:${{ github.sha }}
          docker push rihabsouissi/calcule:v1
          docker push rihabsouissi/calcule:latest
