name: CI - Calculatrice HTML

# Déclenche le workflow à chaque push sur n'importe quelle branche
on:
  push:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js (utile si tu veux utiliser des outils JS)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
